[package]
name = "keypost-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "^0.13"
curve25519-dalek = { version = "^3.1", default-features = false, features = ["std"] }
opaque-ke = "^0.5"
rpassword = "^5.0"
rustyline = "^8.2"
sha2 = "^0.9"